/** массив с данными продуктов */
export const PRODUCTS: Product[] = [
    {
        id: 1,
        title: 'iPhone 9',
        sex: 'any',
        color: ['blue'],
        sizes: ['S'],
        description: [
            'Материал: 100% хлопок',
            'Страна-производитель: Япония',
            'Стираный деним плотностью 12,5 oz',
            'Свободный крой',
            'Прямой силуэт',
            'Высокая посадка',
            'Шлевки для ремня',
            'Застежка на болты',
            '3 боковых кармана',
            '2 задних кармана',
            'Фирменный патч',
        ],
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: 'Apple',
        category: 'smartphones',
        thumbnail: 'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
        images: [
            'https://i.dummyjson.com/data/products/1/1.jpg',
            'https://i.dummyjson.com/data/products/1/2.jpg',
            'https://i.dummyjson.com/data/products/1/3.jpg',
            'https://i.dummyjson.com/data/products/1/4.jpg',
            'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
        ],
    },
    {
        id: 2,
        title: 'testITEM',
        sex: 'any',
        color: ['blue'],
        sizes: ['S'],
        description: [
            'Материал: 100% хлопок',
            'Страна-производитель: Япония',
            'Стираный деним плотностью 12,5 oz',
            'Свободный крой',
            'Прямой силуэт',
            'Высокая посадка',
            'Шлевки для ремня',
            'Застежка на болты',
            '3 боковых кармана',
            '2 задних кармана',
            'Фирменный патч',
        ],
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: 'Apple',
        category: 'smartphones',
        thumbnail: 'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
        images: [
            'https://i.dummyjson.com/data/products/1/1.jpg',
            'https://i.dummyjson.com/data/products/1/2.jpg',
            'https://i.dummyjson.com/data/products/1/3.jpg',
            'https://i.dummyjson.com/data/products/1/4.jpg',
            'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
        ],
    },
];
